# Generated by Django 5.0.7 on 2026-05-06 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_images', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=100)),
                ('rule_index', models.IntegerField()),
                ('batch_id', models.IntegerField()),
                ('large_sub_batch', models.IntegerField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deadline', models.DateTimeField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'task_type', 'rule_index', 'batch_id', 'large_sub_batch')},
            },
        ),
        migrations.CreateModel(
            name='LabelingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('labels_completed', models.IntegerField(default=0)),
                ('batch_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='label_images.batchassignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labeling_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RuleExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=100)),
                ('rule_index', models.IntegerField()),
                ('label', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['task_type', 'rule_index', 'label'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('labeler', 'Labeler')], default='labeler', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
