# Generated by Django 5.0.7 on 2026-05-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_images', '0002_batchassignment_labelingsession_ruleexample_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
