# Generated by Django 5.0.7 on 2026-05-12 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label_images', '0004_workforce_management'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='goldstandardlabel',
            new_name='label_image_task_ty_ea8543_idx',
            old_name='label_ima_task_ty_gold_idx',
        ),
    ]
