# Generated by Django 5.0.7 on 2026-05-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label_images', '0005_rename_label_ima_task_ty_gold_idx_label_image_task_ty_ea8543_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdjudicationDecision',
        ),
    ]
