# Generated by Django 5.0.7 on 2026-05-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_images', '0006_remove_adjudication'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchassignment',
            name='is_training',
            field=models.BooleanField(default=False, help_text='Training batch — shows correct answers after labeler responds.'),
        ),
    ]
