# Generated by Django 5.0.7 on 2026-05-13 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_images', '0007_add_is_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=100)),
                ('rule_index', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, help_text="Grouping label shown as a tab, e.g. 'Asset Type', 'Clip Art Type'.", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'display_order', 'rule_index'],
                'unique_together': {('task_type', 'rule_index')},
            },
        ),
        migrations.CreateModel(
            name='RuleDirective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directives', to='label_images.ruleguide')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('guide', 'number')},
            },
        ),
        migrations.CreateModel(
            name='RuleReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], help_text='Whether this image is a YES or NO example.', max_length=10)),
                ('display_order', models.IntegerField(default=0)),
                ('directive', models.ForeignKey(blank=True, help_text='If set, image is shown next to this specific directive.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='label_images.ruledirective')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='label_images.ruleguide')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
