# Generated by Django 5.0.7 on 2026-05-14 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_images', '0008_rule_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingBatchAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.BigIntegerField()),
                ('image_link', models.CharField(max_length=500)),
                ('correct_label', models.IntegerField(help_text='Reconciled label: 1=yes, 0=no')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_assets', to='label_images.batchassignment')),
            ],
            options={
                'indexes': [models.Index(fields=['assignment'], name='label_image_assignm_936b61_idx')],
                'unique_together': {('assignment', 'asset_id')},
            },
        ),
    ]
