# Generated by Django 5.0.7 on 2026-05-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_images', '0011_training_pay_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchassignment',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
