# Generated by Django 5.0.7 on 2026-05-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label_images', '0013_training_label_response'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='traininglabelresponse',
            new_name='label_image_assignm_18a569_idx',
            old_name='label_image_assignm_8a3f2d_idx',
        ),
    ]
