# Generated by Django 5.0.7 on 2026-05-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_images', '0014_rename_label_image_assignm_8a3f2d_idx_label_image_assignm_18a569_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelingsession',
            name='active_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
