# Generated by Django 5.0.7 on 2026-05-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_images', '0015_active_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.BigIntegerField()),
                ('task_type', models.CharField(max_length=100)),
                ('rule_index', models.IntegerField()),
                ('labeler_id', models.CharField(max_length=150)),
                ('original_answer', models.CharField(max_length=10)),
                ('correct_answer', models.CharField(max_length=10)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['labeler_id'], name='label_image_labeler_f41636_idx'), models.Index(fields=['task_type', 'rule_index'], name='label_image_task_ty_d2b49a_idx')],
                'unique_together': {('asset_id', 'task_type', 'rule_index', 'labeler_id')},
            },
        ),
    ]
