# Generated by Django 5.0.7 on 2026-06-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_images', '0016_label_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchassignment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
