# Generated by Django 5.0.7 on 2026-08-12 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_images', '0017_paid_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=100)),
                ('rule_index', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_exemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'task_type', 'rule_index')},
            },
        ),
    ]
