TRADITIONAL_MEDIA = [
    "watercolor",
    "watercolour",
    "aquarelle",
    "gouache",
    "oil painting",
    "oil paint",
    "acrylic",
    "pastel drawing",
    "soft pastel",
    "oil pastel",
    "chalk",
    "chalkboard",
    "blackboard",
    "charcoal",
    "graphite",
    "pencil",
    "pencil sketch",
    "colored pencil",
    "coloured pencil",
    "pen and ink",
    "ink",
    "inked",
    "india ink",
    "ink wash",
    "sumi",
    "sumi-e",
    "ballpoint",
    "marker",
    "copic",
    "felt tip",
    "crayon",
    "airbrush",
    "spray paint",
    "tempera",
]

# ---------------------------------------------------------------------------
# PRINT & CRAFT TECHNIQUES
# ---------------------------------------------------------------------------
PRINT_AND_CRAFT = [
    "woodcut",
    "woodblock",
    "linocut",
    "lino print",
    "block print",
    "etching",
    "engraving",
    "engraved",
    "vintage engraving",
    "lithograph",
    "screen print",
    "silkscreen",
    "risograph",
    "riso",
    "letterpress",
    "stencil",
    "rubber stamp",
    "postage stamp",
    "halftone",
    "benday",
    "ben-day dots",
    "foil",
    "gold foil",
    "rose gold foil",
    "metallic foil",
    "glitter",
    "sequin",
    "rhinestone",
    "bling",
    "embroidery",
    "embroidered",
    "stitched",
    "cross stitch",
    "needlepoint",
    "patch",
    "applique",
    "felt",
    "knit",
    "knitted",
    "crochet",
    "quilt",
    "patchwork",
    "papercut",
    "paper cut",
    "cut paper",
    "kirigami",
    "papel picado",
    "origami",
    "collage",
    "decoupage",
    "mosaic",
    "stained glass",
    "batik",
    "tie dye",
    "tie-dye",
    "tiedye",
    "macrame",
    "pyrography",
    "wood burning",
    "laser cut",
    "alcohol ink",
    "acrylic pour",
    "fluid art",
    "pour painting",
    "marbled",
    "marbling",
    "resin",
]

# ---------------------------------------------------------------------------
# DIGITAL RENDERING STYLES
# ---------------------------------------------------------------------------
DIGITAL_RENDERING = [
    "flat design",
    "flat style",
    "flat vector",
    "flat illustration",
    "line art",
    "lineart",
    "line drawing",
    "monoline",
    "single line",
    "one line",
    "continuous line",
    "doodle",
    "sketch",
    "sketchy",
    "hand drawn",
    "hand-drawn",
    "handdrawn",
    "hand painted",
    "cartoon",
    "toon",
    "comic",
    "comic book",
    "manga",
    "anime",
    "chibi",
    "kawaii",
    "pixel art",
    "8-bit",
    "8bit",
    "16-bit",
    "pixelated",
    "voxel",
    "low poly",
    "lowpoly",
    "polygonal",
    "isometric",
    "3d",
    "3d render",
    "cgi",
    "claymation",
    "clay render",
    "plasticine",
    "realistic",
    "photorealistic",
    "hyperrealistic",
    "semi-realistic",
    "stylized",
    "minimalist",
    "minimal",
    "abstract",
    "silhouette",
    "gradient",
    "mesh gradient",
    "duotone",
    "tritone",
    "pop art",
    "cel shaded",
    "cel shading",
    "toon shading",
    "painterly",
    "digital painting",
    "concept art",
    "glassmorphism",
    "frosted glass",
    "neumorphism",
    "skeuomorphic",
    "long shadow",
    "sticker style",
    "die cut",
    "die-cut",
    "emoji style",
    "emoticon",
    "stick figure",
    "whiteboard",
    "coloring page",
    "colouring page",
    "coloring book",
    "zentangle",
    "mandala",
    "memphis",
    "memphis design",
    "bauhaus",
    "vaporwave",
    "synthwave",
    "retrowave",
    "outrun",
    "cyberpunk",
    "glitch",
    "glitch art",
    "vhs",
    "psychedelic",
    "groovy",
    "trippy",
    "ligne claire",
    "mascot",
    "sports mascot",
]

# ---------------------------------------------------------------------------
# ICON-INDUSTRY VOCABULARY (Flaticon / Noun Project dialect)
# ---------------------------------------------------------------------------
ICON_VOCAB = [
    "outline icon",
    "line icon",
    "lineal",
    "linear",
    "filled",
    "solid",
    "glyph",
    "flat icon",
    "lineal color",
    "two-tone",
    "two tone",
    "rounded",
    "sharp",
    "badge",
    "emblem",
    "crest",
    "heraldic",
    "heraldry",
    "monogram",
    "logotype",
]

# ---------------------------------------------------------------------------
# LINE & STROKE TREATMENT
# ---------------------------------------------------------------------------
LINE_AND_STROKE = [
    "thick line",
    "bold line",
    "heavy outline",
    "thin line",
    "fine line",
    "fineline",
    "brush stroke",
    "brushstroke",
    "dry brush",
    "drybrush",
    "crosshatch",
    "cross-hatch",
    "hatching",
    "hatched",
    "stipple",
    "stippling",
    "dotwork",
    "pointillism",
    "contour",
    "scribble",
]

# ---------------------------------------------------------------------------
# TEXTURE & SURFACE
# ---------------------------------------------------------------------------
TEXTURE_AND_SURFACE = [
    "grunge",
    "grungy",
    "distressed",
    "worn",
    "weathered",
    "textured",
    "grain",
    "grainy",
    "paper texture",
    "kraft paper",
    "old paper",
    "parchment",
    "torn paper",
    "ripped paper",
    "splatter",
    "paint splatter",
    "splash",
    "watercolor splash",
    "drip",
    "dripping",
    "smudge",
    "smeared",
    "shabby",
    "shabby chic",
    "glossy",
    "shiny",
    "chrome",
    "metallic",
    "gold",
    "silver",
    "copper",
    "bronze",
    "rose gold",
    "holographic",
    "iridescent",
    "pearlescent",
    "matte",
    "glow",
    "glowing",
    "neon glow",
    "sparkle",
    "shimmer",
    "dreamy",
    "ethereal",
    "blurred",
    "soft",
    "ombre",
    "smoke",
    "smoky",
]

# ---------------------------------------------------------------------------
# COLOR-TREATMENT TERMS (lower priority as group keys -- looser families;
# you likely already cover a lot of this via PC1)
# ---------------------------------------------------------------------------
COLOR_TREATMENT = [
    "black and white",
    "b&w",
    "bw",
    "monochrome",
    "monochromatic",
    "grayscale",
    "greyscale",
    "sepia",
    "muted",
    "dusty",
    "earth tone",
    "earthy",
    "terracotta",
    "neutral",
    "jewel tone",
    "vibrant",
    "bright",
    "bold colors",
    "colorful",
    "rainbow",
    "neon",
    "dark",
    "moody",
    "golden",
]

# ---------------------------------------------------------------------------
# DIMENSIONALITY & DRAFTING
# ---------------------------------------------------------------------------
DIMENSIONALITY_AND_DRAFTING = [
    "geometric",
    "wireframe",
    "blueprint",
    "technical drawing",
    "schematic",
    "diagram",
    "patent print",
    "patent drawing",
    "architectural",
    "axonometric",
    "papercraft",
    "layered paper",
    "paper layers",
    "shadow box",
    "2d",
]

# ---------------------------------------------------------------------------
# ERA & DESIGN MOVEMENTS
# ---------------------------------------------------------------------------
ERA_AND_MOVEMENTS = [
    "vintage",
    "retro",
    "antique",
    "old fashioned",
    "nostalgic",
    "old school",
    "victorian",
    "edwardian",
    "art nouveau",
    "art deco",
    "deco",
    "gatsby",
    "mid century",
    "mid-century",
    "midcentury",
    "atomic",
    "atomic age",
    "space age",
    "retro futurism",
    "retrofuturism",
    "50s",
    "fifties",
    "60s",
    "sixties",
    "mod",
    "flower power",
    "hippie",
    "70s",
    "seventies",
    "disco",
    "80s",
    "eighties",
    "90s",
    "nineties",
    "y2k",
    "2000s",
    "medieval",
    "renaissance",
    "baroque",
    "rococo",
    "gothic",
    "goth",
    "blackletter",
    "greco-roman",
    "greek key",
    "americana",
    "pin up",
    "pinup",
    "rockabilly",
]

# ---------------------------------------------------------------------------
# AESTHETIC SUBCULTURES & TREND STYLES
# (Etsy-era SEO -- medium precision, spot-check dependent)
# ---------------------------------------------------------------------------
AESTHETIC_SUBCULTURES = [
    "boho",
    "bohemian",
    "boho chic",
    "farmhouse",
    "rustic",
    "country",
    "primitive",
    "cottagecore",
    "cottage core",
    "french country",
    "scandinavian",
    "scandi",
    "nordic",
    "hygge",
    "japandi",
    "industrial",
    "street art",
    "graffiti",
    "steampunk",
    "fairycore",
    "goblincore",
    "dark academia",
    "light academia",
    "kidcore",
    "coquette",
    "whimsical",
    "fairytale",
    "storybook",
    "enchanted",
    "magical",
    "spooky",
    "creepy cute",
    "pastel goth",
    "creepy kawaii",
    "punk",
    "zine",
    "ransom note",
    "preppy",
    "varsity",
    "collegiate",
    "letterman",
    "maximalist",
    "glam",
    "luxury",
    "luxe",
    "elegant",
    "chic",  # weakest tier -- expect low pass rate
]

# ---------------------------------------------------------------------------
# CULTURAL & REGIONAL TRADITIONS
# ---------------------------------------------------------------------------
CULTURAL_AND_REGIONAL = [
    "ukiyo-e",
    "ukiyoe",
    "japanese woodblock",
    "chinoiserie",
    "chinese ink",
    "chinese painting",
    "folk art",
    "folk",
    "folklore",
    "naive art",
    "otomi",
    "talavera",
    "day of the dead",
    "dia de los muertos",
    "mehndi",
    "henna",
    "rangoli",
    "madhubani",
    "persian miniature",
    "moroccan tile",
    "iznik",
    "celtic",
    "celtic knot",
    "khokhloma",
    "gzhel",
    "ankara",
    "kente",
    "mudcloth",
    "wax print",
    "dot painting",
    "tapa",
    "southwestern",
    "byzantine",
    "hieroglyphic",
    "tarot",
    "tarot card",
    # NOTE: bare "tribal" / "ethnic" deliberately excluded -- too vague as
    # group keys or search facets; prefer the specific tradition names above.
]

# ---------------------------------------------------------------------------
# PRODUCT-FORMAT TERMS THAT IMPLY A LOOK
# ---------------------------------------------------------------------------
PRODUCT_FORMAT = [
    "coloring page",  # implies: black outline, no fill
    "digital stamp",
    "digistamp",  # implies: line art
    "cut file",
    "cricut",
    "silhouette cameo",
    "glowforge",
    "laser ready",
    "htv",  # implies: flat mono silhouette
    "sublimation",
    "waterslide",
    "dtf",  # implies: vivid full-color raster
    "screen print transfer",  # implies: limited-color bold
    "planner sticker",  # implies: white-border die cut
    "seamless pattern",
    "repeat pattern",
    "tileable",
    "surface pattern",
    "digital paper",  # pattern format
    "procreate",  # implies: hand-drawn digital
    "photo overlay",
    "split monogram",
    "frame",
    "wreath",
    "border",
    "divider",
    "corner",
    "banner",  # layout elements -- weak style, useful facets
]

# ---------------------------------------------------------------------------
# TYPOGRAPHY STYLES (if word-art / lettering is in the catalog)
# ---------------------------------------------------------------------------
TYPOGRAPHY_STYLES = [
    "script",
    "cursive",
    "calligraphy",
    "hand lettering",
    "brush lettering",
    "serif",
    "sans serif",
    "old english",
    "bubble letters",
    "stencil font",
    "western",
    "saloon font",
    "retro script",
    "groovy font",
    "3d letters",
]

# ---------------------------------------------------------------------------
# PROVENANCE (not a style -- use as a group SPLITTER, e.g. AI "watercolor"
# vs. scanned watercolor look systematically different)
# ---------------------------------------------------------------------------
PROVENANCE_SPLIT_TERMS = [
    "ai generated",
    "ai art",
    "midjourney",
]

# ---------------------------------------------------------------------------
# CATEGORY INDEX
# Groups the lists above under a type name so terms can be filtered by type on
# the style analysis page. A term may belong to more than one type (currently
# only "coloring page", which is both a rendering style and a product format).
# ---------------------------------------------------------------------------
STYLE_TERM_CATEGORIES = {
    "TRADITIONAL_MEDIA": TRADITIONAL_MEDIA,
    "PRINT_AND_CRAFT": PRINT_AND_CRAFT,
    "DIGITAL_RENDERING": DIGITAL_RENDERING,
    "ICON_VOCAB": ICON_VOCAB,
    "LINE_AND_STROKE": LINE_AND_STROKE,
    "TEXTURE_AND_SURFACE": TEXTURE_AND_SURFACE,
    "COLOR_TREATMENT": COLOR_TREATMENT,
    "DIMENSIONALITY_AND_DRAFTING": DIMENSIONALITY_AND_DRAFTING,
    "ERA_AND_MOVEMENTS": ERA_AND_MOVEMENTS,
    "AESTHETIC_SUBCULTURES": AESTHETIC_SUBCULTURES,
    "CULTURAL_AND_REGIONAL": CULTURAL_AND_REGIONAL,
    "PRODUCT_FORMAT": PRODUCT_FORMAT,
    "TYPOGRAPHY_STYLES": TYPOGRAPHY_STYLES,
    "PROVENANCE_SPLIT_TERMS": PROVENANCE_SPLIT_TERMS,
}

TERM_TO_CATEGORIES = {}
for _category, _terms in STYLE_TERM_CATEGORIES.items():
    for _term in _terms:
        TERM_TO_CATEGORIES.setdefault(_term.strip().lower(), []).append(_category)


def categories_for_term(term):
    """Type names a term belongs to, or ``["UNCATEGORIZED"]`` if it matches none."""
    return TERM_TO_CATEGORIES.get((term or "").strip().lower()) or ["UNCATEGORIZED"]
